version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: junbs_profile
      POSTGRES_PASSWORD: dpaldi1004!
      POSTGRES_DB: myprofile_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
