import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Container from "@/components/Container";
import SessionWrapper from "@/components/SessionWrapper";

export const metadata: Metadata = {
  title: "junb's Frofile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <SessionWrapper>
          <Navbar />
          <Container>{children}</Container>
        </SessionWrapper>
      </body>
    </html>
  );
}
